name: Deploy Website 🚀
on:
  push:
    branches:
      - src
jobs:
  Build-N-Deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set URL 🔗
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Deploy to GH Pages Branch (main) 🔧 # To deploy website to GH Pages
        run: npm run deploy
        
