name: Deploy Website 🚀
on:
  push:
    branches:
      - src
jobs:
  Build-N-Deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set URL 🔗 # To set repo URL to avoid errors like https://github.com/adithyaakrishna/adithyaakrishna.github.io/issues/83
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
      - name: Check Cache 👀 # Checks yarn cache and use it for dependencies install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Deploy to GH Pages Branch (main) 🔧 # To deploy website to GH Pages
        run: npm run deploy
        
